ALTER TABLE messages ADD COLUMN IF NOT EXISTS media_type VARCHAR DEFAULT NULL;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS media_duration INTEGER DEFAULT NULL;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS file_name VARCHAR DEFAULT NULL;
ALTER TABLE messages ADD COLUMN IF NOT EXISTS file_size INTEGER DEFAULT NULL;
